/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prieto.manuel.maven.clinicaveterinaria.igu;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prieto.manuel.maven.clinicaveterinaria.logica.Controladora;
import prieto.manuel.maven.clinicaveterinaria.logica.Mascota;

/**
 *
 * @author G513
 */
public class VerDatos extends javax.swing.JFrame {
    
    Controladora control = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerDatos.class.getName());

    /**
     * Creates new form Principal
     */
    public VerDatos() {
        // Inicializamos la controladora antes de initComponents
        // porque cargarTabla() la necesita cuando la ventana abre
        control = new Controladora();
        initComponents();
        // Cargamos los datos de la BD al abrir la ventana
        cargarTabla();
        cargarImagen();
        
         // cuando el usuario cierra la ventana, volvemos a mostrar principal
         
         addWindowListener(new WindowAdapter(){
             
             @Override
             public void windowClosing(WindowEvent evt){
                 Principal ventana = new Principal();
                 ventana.setLocationRelativeTo(null);
                 ventana.setVisible(true);
             }
             
         });
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrincipal = new javax.swing.JTable();
        btnVerHistorial = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dubai", 0, 48)); // NOI18N
        jLabel1.setText("Visualización de Datos");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Datos de las mascotas: ");

        tablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPrincipal);

        btnVerHistorial.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnVerHistorial.setText("Ver Historial");
        btnVerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                    .addComponent(btnVerHistorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
        // TODO add your handling code here:
        if(tablaPrincipal.getRowCount() > 0){
            if(tablaPrincipal.getSelectedRow() != -1){
                
                // Columna = 0 mum_cliente (PK mascota)
                int numCliente = Integer.parseInt(
                        String.valueOf(tablaPrincipal.getValueAt(tablaPrincipal.getSelectedRow(), 0)));
                // Pasamos el id a verConsultas para abrir el historial de la mascota seleccionada
                VerConsultas pantalla = new VerConsultas(numCliente);
                pantalla.setLocationRelativeTo(null);
                pantalla.setVisible(true);
                this.dispose();
            }else {
                JOptionPane.showMessageDialog(this, "Selecciona una mascota para ver su historial.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay mascotas registradas.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnVerHistorialActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        if (tablaPrincipal.getRowCount() > 0) {
            
            if (tablaPrincipal.getSelectedRow() != -1) {

                // Obtenemos el Id de la fila seleccionada (columna 0)
                int numCliente = Integer.parseInt(String.valueOf(tablaPrincipal.getValueAt(tablaPrincipal.getSelectedRow(), 0)));

                // Pasamos el id a modificarDatos para que cargue esa mascota
                // para abrir el formulario de edicion de los datos de esa mascota en especifico
                ModificarDatos pantalla = new ModificarDatos(numCliente);
                pantalla.setLocationRelativeTo(null);
                pantalla.setVisible(true);
                this.dispose();
                
            } else {
                JOptionPane.showMessageDialog(this, "No selecciono ninguna mascota.", "Error al editar", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "No hay mascotas para editar.", "Error al editar", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEditarActionPerformed
    
    private void cargarTabla() {
        // DefaultTableModel nos permite construir una tabla dinamicamente
        // La sobreescribimos para evitar que el usuario edite celdas directamente

        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Ninguna celda es editable solo se edita desde ModificarDatos
                return false;
            }
        };

        // Definimos los nombres de las Columnas
        String[] titulos = {"Num", "Nombre", "Raza", "Color", "Alérgico", "At. Esp", "Responsable", "Móvil"};
        
        modeloTabla.setColumnIdentifiers(titulos);

        // Llamamos a traer Mascotas 
        // para obtener la lista completa de las mascotas con sus responsables de la BD
        List<Mascota> lista = control.traerMascotas();
        
        if (lista != null) {
            for (Mascota masco : lista) {
                String nombreResp = (masco.getResponsable() != null)
                        ? masco.getResponsable().getNombre() : "Sin Responsable";
                
                String movilResp = (masco.getResponsable() != null) ? masco.getResponsable().getCelResponsable() : "-";

                // Creamos el array con los datos de cada fila
                // Object[]
                Object[] fila = {
                    masco.getNum_cliente(),
                    masco.getNombreMascota(),
                    masco.getRaza(),
                    masco.getColor(),
                    masco.getAlergico(),
                    masco.getAtencionEspecial(),
                    nombreResp,
                    movilResp
                
                };
                
                modeloTabla.addRow(fila);
            }
            
        }
        
        tablaPrincipal.setModel(modeloTabla);
        
    }
    

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Principal ventana = new Principal();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
             //Verificamos que la tabla tenga filas antes de intentar eliminar
        if (tablaPrincipal.getRowCount() > 0) {

            // getSelectedRow retorna -1 si el usuario no selecciono ninguna fila
            if (tablaPrincipal.getSelectedRow() != -1) {

                //Columna 0 de la tabla = num_cliente
                int numCliente = Integer.parseInt(String.valueOf(tablaPrincipal.getValueAt(tablaPrincipal.getSelectedRow(), 0)));

                // llamamos a borrar mascota en la controladora
                control.borrarMascota(numCliente);
                JOptionPane.showMessageDialog(this, "Mascota eliminada correctamente", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
                // Recargamos la tabla para reflejar el cambio 
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "No selecciono ninguna mascota.", "Error al eliminar", JOptionPane.ERROR_MESSAGE);
                
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "No hay mascotas para eliminar.", "Error al eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVerHistorial;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPrincipal;
    // End of variables declaration//GEN-END:variables

      private void cargarImagen() {
     


        // Iconos de los botones 
   

        URL urlVolver = getClass().getResource("/imagenes/volver.png");

        if (urlVolver != null) {
            btnVolver.setIcon(new ImageIcon(urlVolver));
        }
        
        URL urlEliminar= getClass().getResource("/imagenes/eliminar.png");
        
        btnEliminar.setIcon(new ImageIcon(urlEliminar));
        
        URL urlEditar = getClass().getResource("/imagenes/editar.png");
        
        btnEditar.setIcon(new ImageIcon(urlEditar));
        
        
    }

}
